version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    expose:
      - "27017"

  postgres:
    image: pgvector/pgvector:pg16 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sitemine 
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
      - postgres

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb
      - postgres

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    build: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web

volumes:
  db-data:
  pg-db-data: