version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - app-network
    expose:
      - "6379"

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks:
      - app-network
    expose:
      - "27017"

  web:
    build: .
    command: node dist/main.js
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.web.priority=20"

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./frontend
    depends_on:
      - web
    networks:
      - app-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.frontend.priority=10"

  widget:
    build: ./widget
    depends_on:
      - web
    networks:
      - app-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.widget.rule=PathPrefix(`/widget`)"
      - "traefik.http.routers.widget.entrypoints=web"
      - "traefik.http.services.widget.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.widget.priority=30"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true
    name: dokploy-network
